# Generated by Django 4.1 on 2022-08-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_id_alter_screen_id_alter_show_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('name', 'theatre')},
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('screen', 'movie', 'start')},
        ),
    ]
